# Generated by Django 5.1.3 on 2024-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uploadedimage_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('customer_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
